services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NEW_RELIC_LICENSE_KEY="CDBDACAFA02D255E810E9227DD4206BE1666AAD13ACBEAA5FE5A9EDED60711FA"
