name: Develop Workflow

permissions:
  contents: write
  pull-requests: write

on:
  push:
    branches:
      - develop

jobs:
  build-and-merge:
    runs-on: [self-hosted, windows]

    steps:
      - name: Checkout test branch
        uses: actions/checkout@v3
        with:
          ref: test
          token: ${{ secrets.GH_PAT }}
          fetch-depth: 0  # importante para permitir merge

      - name: Stop and remove existing container (if any)
        shell: pwsh
        run: |
          if (my-app-develop) {
            docker stop my-app-develop
            docker rm my-app-develop
         } else {
            Write-Host "No existing container to stop"
            }

      - name: Build Docker image
        run: docker build -t my-app:develop .

      - name: Run Docker container
        run: docker run -d -p 3001:3000 --name my-app-develop my-app:develop

      - name: Configure Git
        run: |
          git config --global user.email "github-actions@github.com"
          git config --global user.name "GitHub Actions"

      - name: Merge develop into test
        run: |
          git fetch origin develop
          git merge origin/develop --no-ff -m "Auto-merge develop into test"
          git push origin test
