name: Main Workflow

on:
  push:
    branches:
      - main

jobs:
  build-and-merge:
    runs-on: [self-hosted, windows]

    steps:
      - name: Checkout main branch
        uses: actions/checkout@v3
        with:
          ref: main
          token: ${{ secrets.GH_PAT }}
          fetch-depth: 0  # importante para permitir merge

      - name: Build Docker image
        run: docker build -t my-app:main .

      - name: Run Docker container
        run:  |
          $container = docker ps -a --format '{{.Names}}' | Select-String -Pattern 'my-app-main'
          if ($container) {
            docker stop my-app-main
            docker rm my-app-main
            }
          else{
            Write-Host "No existe el contenedor"
          }
          docker run -d -p 3000:3000 --name my-app-main `
            -e NEW_RELIC_LICENSE_KEY=${{ secrets.NEW_RELIC_LICENSE_KEY }} `
            my-app:main
          
      - name: Login to Docker Hub
        run: echo $env:DOCKER_PASSWORD | docker login -u $env:DOCKER_USERNAME --password-stdin
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

      - name: Tag Docker image
        run: docker tag my-app:main docker.io/${{ secrets.DOCKER_USERNAME }}/my-app:main

      - name: Push Docker image to Docker Hub
        run: docker push docker.io/${{ secrets.DOCKER_USERNAME }}/my-app:main

      - name: Trigger deploy on Render
        run: curl -X POST ${{ secrets.RENDER_DEPLOY_HOOK_URL }}

      - name: Configure Git
        run: |
          git config --global user.email "github-actions@github.com"
          git config --global user.name "GitHub Actions"
